### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by man4567890** [tedpearson/weather2influxdb#2]
Hi
My config is setup as follow
pi@ra-helios-stats:~/weather $ cat config/weather2influxdb.yaml 
locations:
  - name: xxxxxx
    latitude: -2x.xxxx
    longitude: 2x.xxxx

influxdb:
  host: http://localhost:8086
  user: weather
  password: xxxxxxxxxxxx
  database: weather

forecast:
  measurement_name: forecast
  history:
    enabled: yes
    retention_policy: history_rp
    measurement_name: forecast_history

astronomy:
  enabled: no
  measurement_name: astronomy

sources:
  enabled:
    - visualcrossing
  visualcrossing:
    key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

http_cache_dir: /tmp/weather2influxdb-cache
pi@ra-helios-stats:~/weather $ 

The Grafana sources are connected and tested ok
But when I run the binary I get

pi@ra-helios-stats:~/weather $ ./weather2influxdb-linux-arm 
2021/04/19 15:55:59 Getting VisualCrossing forecast
2021/04/19 15:56:01 Writing 378 points to "forecast" in InfluxDB for "visualcrossing"
2021/04/19 15:56:01 influxdb2client E! Write error: 404 Not Found: 404 page not found

2021/04/19 15:56:01 404 Not Found: 404 page not found

github.com/tedpearson/weather2influxdb/influx.(*Writer).WriteMeasurements
	/home/runner/work/weather2influxdb/weather2influxdb/influx/influx.go:29
main.App.RunForecast
	/home/runner/work/weather2influxdb/weather2influxdb/main.go:86
main.main
	/home/runner/work/weather2influxdb/weather2influxdb/main.go:53
runtime.main
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/proc.go:204
runtime.goexit
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/asm_arm.s:857
2021/04/19 15:56:01 Writing 378 points to "forecast_history" in InfluxDB for "visualcrossing"
2021/04/19 15:56:01 influxdb2client E! Write error: 404 Not Found: 404 page not found

2021/04/19 15:56:01 404 Not Found: 404 page not found

github.com/tedpearson/weather2influxdb/influx.(*Writer).WriteMeasurements
	/home/runner/work/weather2influxdb/weather2influxdb/influx/influx.go:29
main.App.RunForecast
	/home/runner/work/weather2influxdb/weather2influxdb/main.go:99
main.main
	/home/runner/work/weather2influxdb/weather2influxdb/main.go:53
runtime.main
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/proc.go:204
runtime.goexit
	/opt/hostedtoolcache/go/1.15.7/x64/src/runtime/asm_arm.s:857
pi@ra-helios-stats:~/weather $ 

Could you point me in the right direction please

**Comment by tedpearson** [comment]
Have you created the database "weather" in influxdb yet? I believe you can get a 404 if the database has not been created.

**Comment by tedpearson** [comment]
Closing issue, no response in 2.5 months.
